name: run-benchmarks
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags: '*'

jobs:
  Run-benchmark-arrays:
    runs-on: ubuntu-latest
    steps:
       - name: Cancel ongoing test runs for previous commits
         uses: styfle/cancel-workflow-action@0.11.0
       - uses: actions/checkout@v3
       - name: setup-benchmarks
         run: bash ./.github/setup.sh
       - name: run-benchmarks
         run: bash ./.github/run-arrays.sh
  Update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2      
      - name: Run script to update README
        run: bash ./.github/update_readme.sh
      - name: Commit and push if changed
        run: |
          git diff
          git add README.md
          git commit -m "Update README" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          