name: run-benchmarks
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags: '*'

jobs:
  Run-benchmark-arrays:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel ongoing test runs for previous commits
        uses: styfle/cancel-workflow-action@0.11.0
      - uses: actions/checkout@v4
      - name: setup-benchmarks
        run: bash ./.github/setup.sh
      - name: run-benchmarks
        run: bash ./.github/run-arrays.sh
      - name: Run script to update README
        run: bash ./.github/update_readme.sh
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"        
      - name: Commit and push if changed
        run: |
          git commit -am "Automated report"        
          git diff
          git add README.md
          git commit -m "Update README" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          