name: run-benchmarks
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags: '*'

jobs:
  Run-benchmark-arrays:
    runs-on: ubuntu-latest
    steps:
       - name: Cancel ongoing test runs for previous commits
         uses: styfle/cancel-workflow-action@0.11.0
       - uses: actions/checkout@v3
       - name: setup-benchmarks
         run: bash ./.github/setup.sh
       - name: run-benchmarks
         run: bash ./.github/run-arrays.sh